# Example wrangler.toml
# Fill in values or rely on GitHub Actions to pass account-id and name.
name = "my-mail-proxy-worker"
main = "./cloudflare-worker.js"
compatibility_date = "2026-01-01"

# If you prefer to keep account id here, replace with your Cloudflare account id
# account_id = "your-account-id"

# Type "javascript" for a single-file worker
type = "javascript"
